
#ifndef WEB_PAGES_H
#define WEB_PAGES_H

#include <Arduino.h>

const char head_1[] PROGMEM =
  "<!DOCTYPE html>"
  "<html lang=\"es\">"
    "<head>"
      "<meta charset=\"UTF-8\">"
      "<title>Control Rover</title>"
      "<link rel=\"icon\" href=\"data:,\">"
      "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
      "<style>"
        "body {font-family:Arial, sans-serif; text-align:center; margin:8px; background:#f5f5f5;}"
        "button {padding:8px 12px; font-size:14px; margin:4px; touch-action:none; -webkit-user-select:none; user-select:none;}"
        "p {font-size:13px; color:#666; margin:4px 0;}"
        ".panel {background:#fff; border:1px solid #ddd; border-radius:10px; padding:10px; box-sizing:border-box;}"
        "#mainLayout {display:grid; grid-template-columns:380px 1fr; gap:10px; max-width:1100px; margin:0 auto; align-items:start;}"
        "#leftCol, #rightCol {display:flex; flex-direction:column; gap:10px;}"
        ".row {display:flex; align-items:center; justify-content:center; gap:6px; flex-wrap:wrap;}"
        ".indtemp {display:flex; justify-content:center; gap:12px; margin:6px 0; flex-wrap:wrap;}"
        ".indicator {text-align:center;}"
        ".car {width:auto; height:auto; max-width:52px; max-height:52px; transition:transform 0.3s ease; transform-origin:center center; object-fit:contain;}"
        ".carminus {width:auto; height:auto; max-width:34px; max-height:34px; transition:transform 0.3s ease; transform-origin:center center; object-fit:contain;}"
        ".bar {width:130px; height:18px; background-color:#e0e0e0; border-radius:10px; overflow:hidden; position:relative; margin:6px auto;}"
        ".barfill {height:100%; background-color:#3498db; width:var(--percent, 0%);}"
        ".bar::after {content: attr(data-value); font-size:12px; position:absolute; top:50%; left:50%; transform:translate(-50%, -50%); color:#444;}"
        "#streamImg {width:360px; height:270px; background:#ddd; object-fit:cover; border-radius:8px;}"
        ".camctrls{margin-top:8px;display:flex;flex-direction:column;gap:8px;}"
        ".camctrls select{padding:6px 8px;font-size:14px;border-radius:6px;border:1px solid #ccc;}"
        ".camctrls .row label{font-size:13px;color:#444;}"
        ".cambtn-secondary{background:#6c757d;color:#fff;}"
        ".cambtn-secondary:hover{background:#5c636a;}"
        ".cambtn-warn{background:#d97706;color:#fff;}"
        ".cambtn-warn:hover{background:#b45309;}"
        "#camStatus{font-size:13px;color:#555;min-height:18px;}"        
        "#radarCanvas {width:300px; height:160px; max-width:100%;}"
        "#topActions {display:flex; justify-content:center; align-items:center; gap:8px; flex-wrap:wrap;}"
        "#wsStatus, #presenceStatus {font-size:16px; margin-top:4px;}"
        "#debugRuedasPanel {margin-top:8px;}"
        ".camnav{width:360px;display:flex;align-items:center;justify-content:space-between;margin:8px auto 0 auto;}"
        ".camnav-center{display:flex;flex-direction:column;gap:6px;align-items:center;justify-content:center;}"
        ".camnav button{min-width:52px;min-height:42px;}"
        "@media (max-width: 900px) {"
          "#mainLayout {grid-template-columns:1fr;}"
          "#streamImg {width:260px; height:195px;}"
          "button {font-size:12px; padding:6px 8px; margin:3px;}"
          ".car {max-width:42px; max-height:42px;}"
          ".carminus {max-width:28px; max-height:28px;}"
          ".bar {width:110px; height:16px;}"
          ".camnav{width:260px;}"
        "}"
      "</style>"
    "</head>"
    "<body>"
      "<div id=\"mainLayout\">"
        "<div id=\"leftCol\">"

        ///////////////////
    "<div class=\"panel\">"
      "<div style=\"display:flex;flex-direction:column;align-items:center;\">"
        "<img id=\"streamImg\" alt=\"cam\" width=\"320\" height=\"240\" loading=\"lazy\" decoding=\"async\">"
        "<div class=\"camnav\">"
          "<button onpointerdown=\"mvD(event,'caml')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">&#9664;</button>"
          "<div class=\"camnav-center\">"
            "<button onpointerdown=\"mvD(event,'camup')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">&#9650;</button>"
            "<button onpointerdown=\"mvD(event,'camdn')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">&#9660;</button>"
          "</div>";

const char head_2[] PROGMEM =
            "<button onpointerdown=\"mvD(event,'camr')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">&#9654;</button>"
          "</div>"
        "</div>"
            "<div class=\"camctrls\">"
              "<div class=\"row\">"
                "<button class=\"cambtn-secondary\" onclick=\"camReconnect()\">Reconectar</button>"
                "<button onclick=\"camSnapshot()\">Foto</button>"
                "<button class=\"cambtn-warn\" onclick=\"camToggleFlash()\">Flash cam</button>"
              "</div>"
              "<div id=\"camStatus\">Cámara no inicializada</div>"
            "</div>"            
          "</div>"

          "<div class=\"panel\">"
            "<canvas id=\"radarCanvas\" width=\"340\" height=\"180\"></canvas>"
          "</div>"
        "</div>"

        "<div id=\"rightCol\">"
          "<div class=\"panel\">"
            "<div class=\"row\">"
              "<button onpointerdown=\"mvD(event,'fl')\" onpointerup=\"stopD(event,'stop')\" onpointercancel=\"stopD(event,'stop')\" onpointerleave=\"stopD(event,'stop')\">Giro Izda</button>"
              "<button onpointerdown=\"mvD(event,'f')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Adelante</button>"
              "<button onpointerdown=\"mvD(event,'fr')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Giro Dcha</button>"
            "</div>"

            "<div class=\"row\">"
              "<button id=\"controlButton8\" onpointerdown=\"mvD(event,'latl')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Lat Izda</button>"
              "<div class=\"indicator\"><img src=\"/carback\" id=\"carelev\" class=\"carminus\"><p>Ala: <span id=\"e\">--</span>°</p></div>"
              "<div class=\"indicator\"><img src=\"/carup\" id=\"carazim\" class=\"car\"><p><span id=\"a\">--</span>°</p></div>"
              "<div class=\"indicator\"><img src=\"/carside\" id=\"cargiro\" class=\"car\"><p>Cab: <span id=\"g\">--</span>°</p></div>"
              "<button onpointerdown=\"mvD(event,'latr')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Lat Dcha</button>"
            "</div>"

            "<div class=\"row\">"
              "<button onpointerdown=\"mvD(event,'rl')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Atras Izda</button>"
              "<button onpointerdown=\"mvD(event,'r')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Atras</button>"
              "<button onpointerdown=\"stopD(event)\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">STOP</button>"
              "<button onpointerdown=\"mvD(event,'rr')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Atras Der</button>"
            "</div>"

            "<div class=\"row\">"
              "<button onpointerdown=\"mvD(event,'rotl')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Rot Izda</button>"
              "<button onpointerdown=\"mvD(event,'rotr')\" onpointerup=\"stopD(event)\" onpointercancel=\"stopD(event)\" onpointerleave=\"stopD(event)\">Rot Dcha</button>"
            "</div>"
          "</div>"

          "<div class=\"panel\">"
            "<div id=\"topActions\">"
              "<button onclick=\"sCom('speedmenos')\">---</button>"
              "<span id=\"sp_needle\">1000</span>"
              "<button onclick=\"sCom('speedmas')\">+++</button>"
              "<button onclick=\"sCom('luces')\">Luces</button>"
              "<button onclick=\"sCom('flash')\">Flash</button>"
              "<a href=\"/setup\"><button>Config</button></a>"
            "</div>"

            "<div id=\"wsStatus\" style=\"color:green;\"></div>"
            "<div id=\"presenceStatus\" style=\"color:#888;\"> </div>"

            "<span id=\"t\" style=\"display:none;\">--</span>"
            "<span id=\"h\" style=\"display:none;\">--</span>"

            "<div class=\"indtemp\">"
              "<div class=\"indicator\">Temp<div id=\"tempBar\" class=\"bar\" data-value=\"0%\"><div class=\"barfill\" style=\"--percent: 0%;\"></div></div></div>"
              "<div class=\"indicator\">Hum<div id=\"humBar\" class=\"bar\" data-value=\"0%\"><div class=\"barfill\" style=\"--percent: 0%;\"></div></div></div>"
            "</div>"

            "<div id=\"debugRuedasPanel\" style=\"display:none;\">"
              "RUEDAS<br>"
              "<button onpointerdown=\"sComDebug('DIF')\" onpointerup=\"sComDebug('stop')\" onpointercancel=\"sComDebug('stop')\" onpointerleave=\"sComDebug('stop')\">DI-F</button>"
              "<button onpointerdown=\"sComDebug('DDF')\" onpointerup=\"sComDebug('stop')\" onpointercancel=\"sComDebug('stop')\" onpointerleave=\"sComDebug('stop')\">DD-F</button><br>"
              "<button onpointerdown=\"sComDebug('DIR')\" onpointerup=\"sComDebug('stop')\" onpointercancel=\"sComDebug('stop')\" onpointerleave=\"sComDebug('stop')\">DI-R</button>"
              "<button onpointerdown=\"sComDebug('DDR')\" onpointerup=\"sComDebug('stop')\" onpointercancel=\"sComDebug('stop')\" onpointerleave=\"sComDebug('stop')\">DD-R</button><br><br>"
              "<button onpointerdown=\"sComDebug('TIF')\" onpointerup=\"sComDebug('stop')\" onpointercancel=\"sComDebug('stop')\" onpointerleave=\"sComDebug('stop')\">TI-F</button>"
              "<button onpointerdown=\"sComDebug('TDF')\" onpointerup=\"sComDebug('stop')\" onpointercancel=\"sComDebug('stop')\" onpointerleave=\"sComDebug('stop')\">TD-F</button><br>"
              "<button onpointerdown=\"sComDebug('TIR')\" onpointerup=\"sComDebug('stop')\" onpointercancel=\"sComDebug('stop')\" onpointerleave=\"sComDebug('stop')\">TI-R</button>"
              "<button onpointerdown=\"sComDebug('TDR')\" onpointerup=\"sComDebug('stop')\" onpointercancel=\"sComDebug('stop')\" onpointerleave=\"sComDebug('stop')\">TD-R</button>"
            "</div>"
          "</div>"
        "</div>"
      "</div>";

const char script_01[] PROGMEM =
  "<script>"
    "let ws;"
    "let r_sp=1000;"
    "function connectWS() {"
      "ws=new WebSocket(`ws://${location.hostname}:81/`);"
      "ws.onopen=()=>{"
        "console.log('WS On');"
        "document.getElementById('wsStatus').innerText='ON';"
        "document.getElementById('wsStatus').style.color='green';"
      "};"
      "ws.onmessage=(event)=> {"
        "try{"
          "let data=JSON.parse(event.data);"
          "if (data.type==='sensor'){"
            "upText('t',data.t);"
            "upText('h',data.h);"
            "upIndDht(data.t,data.h);"
          "}"
          "else if (data.type==='giros'){"
            "upText('a',data.a);"
            "upText('e',data.e);"
            "upText('g',data.g);"
            "upIndGiros(data.a,data.e,data.g,data.dUS1);"
          "}"
          "else if (data.type==='radar'){"
            "upIndRadar(data.ang,data.dis);"
          "}"
          "else if (data.type==='status') {"
            "r_sp = Number(data.speed);"
            "document.getElementById('sp_needle').innerText = Number.isFinite(r_sp) ? Math.round(r_sp) : '--';"
          "}"
          "else if (data.type==='speed') {"
            "r_sp = Number(data.sp);"
            "document.getElementById('sp_needle').innerText = Number.isFinite(r_sp) ? Math.round(r_sp) : '--';"
          "}"
          "else if (data.type==='presence'){"
            "upPresence(data.det);"
          "}"
        "}catch(e) {"
          "console.error('Error datos:',e);"
        "}"
      "};"
      "ws.onclose = () => {"
        "console.log('WS Off');"
        "document.getElementById('wsStatus').innerText='OFF';"
        "document.getElementById('wsStatus').style.color='red';"
        "setTimeout(connectWS, 2000);"
      "};"
      "ws.onerror = (error) => {"
        "console.error('Error WS:', error);"
      "};"
    "}"

    "function upText(id, value) {"
      "const el = document.getElementById(id);"
      "if (!el) return;"
      "if (value === null || value === undefined) {"
        "el.innerText='--';"
        "return;"
      "}"
      "const n = Number(value);"
      "el.innerText = Number.isFinite(n) ? n.toFixed(1) : '--';"
    "}"

    "function sCom(command) {"
      "if (ws && ws.readyState === WebSocket.OPEN) {"
        "if (command === 'stop') {"
          "clearInterval(mvInt);"
          "mvInt = null;"
          "ws.send(command);"
        "} else {"
          "ws.send(command);"
        "}"
      "} else {"
        "console.error('WS Off');"
      "}"
    "}"

    "function upPresence(det) {"
      "const el = document.getElementById('presenceStatus');"
      "if (!el) return;"
      "if (Number(det) === 1) {"
        "el.innerText = 'P';"
        "el.style.color = 'red';"
        "el.style.fontWeight = 'bold';"
      "} else {"
        "el.innerText = ' ';"
        "el.style.color = '#888';"
        "el.style.fontWeight = 'normal';"
      "}"
    "}"

    "connectWS();"

    "let mvInt=null;"
    "function mvD(ev, command, stopCmd='stop') {"
      "if (ev) ev.preventDefault();"
      "clearInterval(mvInt);"
      "sCom(command);"
      "mvInt=setInterval(()=>{ sCom(command);},100);"
    "}"

    "function stopD(ev, stopCmd='stop') {"
      "if (ev) ev.preventDefault();"
      "clearInterval(mvInt);"
      "mvInt=null;"
      "sCom(stopCmd);"
    "}"

    "function upIndDht(t,h) {"
      "const tBFill=document.querySelector('#tempBar .barfill');"
      "const hBFill=document.querySelector('#humBar .barfill');"
      "if (t === null || h === null || !Number.isFinite(Number(t)) || !Number.isFinite(Number(h))) {"
        "tBFill.style.width='0%';"
        "hBFill.style.width='0%';"
        "tBFill.parentElement.setAttribute('data-value','--');"
        "hBFill.parentElement.setAttribute('data-value','--');"
        "return;"
      "}"
      "tBFill.style.width=`${(t/50)*100}%`;"
      "tBFill.parentElement.setAttribute('data-value',`${Number(t).toFixed(1)}°C`);"
      "hBFill.style.width=`${h}%`;"
      "hBFill.parentElement.setAttribute('data-value',`${Number(h).toFixed(1)}%`);"
    "}"

    "function upIndGiros(a,e,g) {"
      "document.getElementById('carazim').style.transform=`rotate(${a}deg)`;"
      "document.getElementById('carelev').style.transform=`rotate(${e}deg)`;"
      "document.getElementById('cargiro').style.transform=`rotate(${g}deg)`;"
      "document.getElementById('a').innerText=a.toFixed(1);"
      "document.getElementById('e').innerText=e.toFixed(1);"
      "document.getElementById('g').innerText=g.toFixed(1);"
    "}"

    "let detections = new Array(181).fill(null);"
    "let radarTargetAng = -90;"
    "let radarDisplayAng = -90;"
    "let radarLastDis = 0;"

    "function upIndRadar(ang, dis) {"
      "const index = Math.round(ang);"
      "if (index >= 0 && index < detections.length) {"
        "detections[index] = dis;"
      "}"
      "radarTargetAng = ang;"
      "radarLastDis = dis;"
    "}"

    "function drawRadar() {"
      "const canvas = document.getElementById('radarCanvas');"
      "const ctx = canvas.getContext('2d');"
      "let diff = radarTargetAng - radarDisplayAng;"
      "if (diff > 180) diff -= 360;"
      "if (diff < -180) diff += 360;"
      "const maxStep = 1.2;"
      "if (Math.abs(diff) <= maxStep) {"
        "radarDisplayAng = radarTargetAng;"
      "} else {"
        "radarDisplayAng += (diff > 0 ? maxStep : -maxStep);"
      "}"
      "ctx.fillStyle = '#006400';"
      "ctx.fillRect(0, 0, canvas.width, canvas.height);"

      "ctx.fillStyle = '#d8ffd8';"
      "ctx.font = '12px Arial';"
      "ctx.textAlign = 'left';"
      "ctx.fillText(`Ang: ${Number.isFinite(Number(radarDisplayAng)) ? radarDisplayAng.toFixed(1) : '--'}°`, 8, 16);"
      "ctx.textAlign = 'right';"
      "ctx.fillText(`Dis: ${Number.isFinite(Number(radarLastDis)) ? (radarLastDis / 10).toFixed(1) : '--'} cm`, canvas.width - 8, 16);"
      "ctx.textAlign = 'left';"

      "const centerX = canvas.width / 2;"
      "const centerY = canvas.height;"
      "const distances = [30, 60, 90, 120, 150];"
      "ctx.lineWidth = 1;"
      "ctx.strokeStyle = '#32CD32';"
      "ctx.fillStyle = 'black';"
      "distances.forEach(function(dist) {"
        "ctx.beginPath();"
        "ctx.arc(centerX, centerY, dist, Math.PI, 2 * Math.PI);"
        "ctx.stroke();"
        "ctx.fillText(dist + ' cm', centerX + 5, centerY - dist);"
      "});"
      "const angleSteps = [0, 30, 60, 90, 120, 150, 180];"
      "ctx.lineWidth = 1;"
      "ctx.strokeStyle = '#90EE90';"
      "angleSteps.forEach(function(angle) {"
        "let angRad = (angle * Math.PI) / 180;"
        "let sweepX = centerX + Math.cos(angRad) * 150;"
        "let sweepY = centerY - Math.sin(angRad) * 150;"
        "ctx.beginPath();"
        "ctx.moveTo(centerX, centerY);"
        "ctx.lineTo(sweepX, sweepY);"
        "ctx.stroke();"
      "});"
      "for (let i = 0; i < detections.length; i++) {"
        "if (detections[i] !== null) {"
          "let angRad = (i * Math.PI) / 180;"
          "let maxDist = 300;"
          "let x = centerX + Math.cos(angRad) * (detections[i] / 2750) * maxDist;"
          "let y = centerY - Math.sin(angRad) * (detections[i] / 2750) * maxDist;"
          "ctx.beginPath();"
          "ctx.arc(x, y, 2, 0, 2 * Math.PI);"
          "ctx.fillStyle = '#90EE90';"
          "ctx.fill();"
        "}"
      "}"
      "let angRad = (radarDisplayAng * Math.PI) / 180;"
      "let sweepX = centerX + Math.cos(angRad) * 150;"
      "let sweepY = centerY - Math.sin(angRad) * 150;"
      "ctx.beginPath();"
      "ctx.moveTo(centerX, centerY);"
      "ctx.lineTo(sweepX, sweepY);"
      "ctx.strokeStyle = 'limegreen';"
      "ctx.lineWidth = 2;"
      "ctx.stroke();"
      "requestAnimationFrame(drawRadar);"
    "}"

    "requestAnimationFrame(drawRadar);"

    "setTimeout(() => {"
      "const img = document.getElementById('streamImg');"
      "img.src = 'http://192.168.4.2:81/stream';"
    "}, 100);"

    "let debugRuedas = false;"
    "function sComDebug(command) {"
      "if (debugRuedas) {"
        "sCom(command);"
      "}"
    "}"
    "function actualizarDebugRuedas() {"
      "const panel = document.getElementById('debugRuedasPanel');"
      "if (panel) {"
        "panel.style.display = debugRuedas ? 'block' : 'none';"
      "}"
    "}"
    "actualizarDebugRuedas();"
    "const CAM_HOST='http://192.168.4.2';"
    "const CAM_STREAM='http://192.168.4.2:81/stream';"
    "let camFlashOn=false;"

    "function camSetStatus(txt,color='#555'){"
      "const e=document.getElementById('camStatus');"
      "if(!e) return;"
      "e.textContent=txt;"
      "e.style.color=color;"
    "}"

    "function camInit(){"
      "const img=document.getElementById('streamImg');"
      "if(!img) return;"
      "img.onload=()=>camSetStatus('Stream activo','#15803d');"
      "img.onerror=()=>camSetStatus('Sin señal de cámara','#b91c1c');"
      "img.src=CAM_STREAM+'?t='+Date.now();"
    "}"

    "function camReconnect(){"
      "const img=document.getElementById('streamImg');"
      "if(!img) return;"
      "camSetStatus('Reconectando cámara...','#b45309');"
      "img.src='';"
      "setTimeout(()=>{"
        "img.src=CAM_STREAM+'?t='+Date.now();"
      "},300);"
    "}"

    "function camSnapshot(){"
      "camSetStatus('Abriendo captura...','#555');"
      "window.open(CAM_HOST+'/capture','_blank');"
    "}"

    "function camControl(varName,val){"
      "camSetStatus('Enviando ajuste a cámara...','#555');"
      "fetch(CAM_HOST+'/control?var='+encodeURIComponent(varName)+'&val='+encodeURIComponent(val))"
        ".then(r=>{"
          "if(!r.ok) throw new Error('control error');"
          "camSetStatus('Ajuste aplicado','#15803d');"
        "})"
        ".catch(()=>camSetStatus('Error al contactar con la cámara','#b91c1c'));"
    "}"

    "function camToggleFlash(){camFlashOn=!camFlashOn;camControl('led_intensity',camFlashOn?255:0);}"
    "function camMirror(el){camControl('hmirror',el.checked?1:0);}"
    "function camFlip(el){camControl('vflip',el.checked?1:0);}"
    "camInit();"

  "</script>"
  "</body>"
  "</html>";

const char setup_page_1[] PROGMEM =
  "<!DOCTYPE html>"
  "<html lang=\"es\">"
  "<head>"
    "<meta charset=\"UTF-8\">"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    "<title>Configuración</title>"
    "<style>"
      "body{font-family:Arial,sans-serif;text-align:center;padding:20px;background:#f5f5f5;color:#222;}"
      ".card{max-width:460px;margin:0 auto;background:#fff;border-radius:10px;padding:20px;box-shadow:0 2px 10px rgba(0,0,0,0.12);}"
      "h2{margin-top:0;}"
      ".row{margin:14px 0;text-align:left;}"
      "label{display:block;margin-bottom:6px;font-weight:bold;}"
      "input,select,button{font-size:16px;border-radius:6px;box-sizing:border-box;}"
      "input,select{width:100%;padding:10px;border:1px solid #bbb;}"
      ".btns{display:flex;gap:10px;flex-wrap:wrap;justify-content:center;margin-top:16px;}"
      "button{padding:10px 16px;border:1px solid #2980b9;background:#3498db;color:white;cursor:pointer;}"
      "button:hover{background:#2980b9;}"
      "button.secondary{background:#7f8c8d;border-color:#6c7a7a;}"
      "button.secondary:hover{background:#6c7a7a;}"
      "button.restart{background:#d97706;}"
      "button.restart:hover{background:#b45309;}"
      ".ssid-list{margin-top:16px;padding:10px;border:1px solid #ccc;background:#fafafa;max-height:180px;overflow-y:auto;border-radius:6px;text-align:left;}"
      ".ssid-item{padding:8px;margin:4px 0;background:#ececec;border-radius:4px;cursor:pointer;}"
      ".ssid-item:hover{background:#dcdcdc;}"
      "#msg{min-height:22px;margin-top:12px;font-weight:bold;}"
      ".small{font-size:13px;color:#666;}"
    "</style>"
  "</head>"
  "<body>"
    "<div class='card'>"
      "<h2>Configuración de red</h2>"
      "<div class='small'>La configuración se lee y guarda desde el backend</div>";

const char setup_page_2[] PROGMEM =
      "<div class='row'>"
        "<label for='modoinic'>Modo de inicio</label>"
        "<select id='modoinic'>"
          "<option value='0'>AP+STA</option>"
          "<option value='1'>AP</option>"
          "<option value='2'>STA</option>"
        "</select>"
      "</div>"

      "<div class='row'>"
        "<label for='ssid'>SSID cliente</label>"
        "<input type='text' id='ssid' placeholder='Red WiFi a la que conectarse'>"
      "</div>"

      "<div class='row'>"
        "<label for='password'>Contraseña cliente</label>"
        "<input type='password' id='password' placeholder='Contraseña WiFi'>"
      "</div>"

      "<div class='btns'>"
        "<button id='searchSSIDButton' onclick='searchSSIDs()'>Buscar SSIDs</button>"
        "<button id='saveButton' onclick='saveData()'>Guardar</button>"
        "<button class='restart' onclick='restartDevice()'>Reiniciar</button>"
        "<button class='secondary' onclick=\"location.href='/'\">Volver</button>"
      "</div>"

      "<div id='msg'></div>"
      "<div class='ssid-list' id='ssidList'></div>"

"<label for='camRes'>Resolución cámara</label>"
"<select id='camRes' onchange='setCamResolution(this.value)'>"
  "<option value='5'>QVGA</option>"
  "<option value='6'>CIF</option>"
  "<option value='8' selected>VGA</option>"
  "<option value='9'>SVGA</option>"
"</select>"
"<div id='camResMsg' style='margin-top:6px;font-size:13px;color:#555;'></div>"

      "<script>"
        "function setMsg(txt,color='black'){"
          "const m=document.getElementById('msg');"
          "m.textContent=txt;"
          "m.style.color=color;"
        "}"

        "function modoEsCliente(v){"
          "return v==='0' || v==='2';"
        "}"

        "function aplicarVisibilidadModo(){"
          "const modo=document.getElementById('modoinic').value;"
          "const ssidRow=document.getElementById('ssid').parentElement;"
          "const passRow=document.getElementById('password').parentElement;"
          "const btnBuscar=document.getElementById('searchSSIDButton');"
          "const visible=modoEsCliente(modo);"
          "ssidRow.style.display=visible?'block':'none';"
          "passRow.style.display=visible?'block':'none';"
          "btnBuscar.style.display=visible?'inline-block':'none';"
          "if(!visible){"
            "document.getElementById('ssidList').innerHTML='';"
          "}"
        "}"

        "function searchSSIDs(){"
          "if(!modoEsCliente(document.getElementById('modoinic').value)){"
            "setMsg('Este modo no usa conexión como cliente','red');"
            "return;"
          "}"
          "setMsg('Buscando redes...','#444');"
          "const ssidList=document.getElementById('ssidList');"
          "ssidList.innerHTML='';"
          "let ws=new WebSocket(`ws://${location.hostname}:81/`);"

          "ws.onopen=()=>{"
            "ws.send('getssids');"
          "};"
///////////////////////
          "ws.onmessage=(event)=>{"
            "let data;"
            "try{"
              "data=JSON.parse(event.data);"
            "}catch(e){"
              "setMsg('Respuesta inválida del servidor','red');"
              "ws.close();"
              "return;"
            "}"

            "let ssids=null;"

            // Caso 1: array puro
            "if(Array.isArray(data)){"
              "ssids=data;"
            "}"
            // Caso 2: objeto del tipo {type:'ssids', list:[...]}
            "else if(data && data.type==='ssids' && Array.isArray(data.list)){"
              "ssids=data.list;"
            "}"
            // Ignorar mensajes de estado, sensor, radar, etc.
            "else{"
              "return;"
            "}"

            "ssidList.innerHTML='';"

            "if(ssids.length===0){"
              "setMsg('No se encontraron redes','red');"
              "ws.close();"
              "return;"
            "}"

            "ssids.forEach(ssid=>{"
              "const d=document.createElement('div');"
              "d.className='ssid-item';"
              "d.textContent=ssid;"
              "d.onclick=()=>{"
                "document.getElementById('ssid').value=ssid;"
                "setMsg('SSID seleccionado: '+ssid,'green');"
              "};"
              "ssidList.appendChild(d);"
            "});"

            "setMsg('Selecciona una red de la lista','green');"
            "ws.close();"
          "};"
//////////////////////////
          "ws.onerror=()=>{"
            "setMsg('Error al buscar SSIDs','red');"
            "ws.close();"
          "};"
        "}"

        "function saveData(){"
          "const modoinic=document.getElementById('modoinic').value;"
          "const ssid=document.getElementById('ssid').value.trim();"
          "const password=document.getElementById('password').value;"

          "if(!['0','1','2'].includes(modoinic)){"
            "setMsg('Modo de inicio no válido','red');"
            "return;"
          "}"

          "if(modoEsCliente(modoinic) && ssid===''){"
            "setMsg('Debes indicar un SSID para el modo cliente','red');"
            "return;"
          "}"

          "const data={modoinic:modoinic,ssid:ssid,password:password};"
          "setMsg('Guardando...','#444');"

          "fetch('/save_config',{"
            "method:'POST',"
            "headers:{'Content-Type':'application/json'},"
            "body:JSON.stringify(data)"
          "})"
          ".then(response=>{"
            "if(!response.ok) throw new Error('Error HTTP');"
            "return response.json();"
          "})"
          ".then(data=>{"
            "if(data && data.ok===false){"
              "setMsg(data.error || 'No se pudo guardar','red');"
            "}else{"
              "setMsg('Configuración guardada','green');"
            "}"
          "})"
          ".catch(error=>{"
            "console.error('Error:',error);"
            "setMsg('No se pudo guardar la configuración','red');"
          "});"
        "}"

        "function loadConfig(){"
          "fetch('/get_config')"
          ".then(response=>{"
            "if(!response.ok) throw new Error('Error HTTP');"
            "return response.json();"
          "})"
          ".then(data=>{"
            "document.getElementById('modoinic').value=(data.modoinic!==undefined && data.modoinic!==null)?String(data.modoinic):'0';"
            "document.getElementById('ssid').value=data.ssid || '';"
            "document.getElementById('password').value='';"
            "aplicarVisibilidadModo();"
            "setMsg('Configuración cargada','green');"
          "})"
          ".catch(error=>{"
            "console.error('Error al cargar la configuración:',error);"
            "aplicarVisibilidadModo();"
            "setMsg('No se pudo cargar la configuración','red');"
          "});"
        "}"

        "document.addEventListener('DOMContentLoaded',()=>{"
          "document.getElementById('modoinic').addEventListener('change',aplicarVisibilidadModo);"
          "loadConfig();"
        "});"

        "async function restartDevice(){"
          "if(!confirm('¿Reiniciar el dispositivo ahora?')) return;"
          "try{"
            "setMsg('Reiniciando dispositivo...', 'green');"
            "await fetch('/restart', { method:'POST' });"
          "}catch(e){"
            "setMsg('Orden de reinicio enviada', 'green');"
          "}"
        "}"
"const CAM_HOST='http://192.168.4.2';"

"function setCamResMsg(txt,color='green'){"
  "const e=document.getElementById('camResMsg');"
  "if(!e) return;"
  "e.textContent=txt;"
  "e.style.color=color;"
"}"

"function setCamResolution(v){"
  "setCamResMsg('Aplicando resolución de cámara...','#b45309');"
  "fetch(CAM_HOST+'/control?var=framesize&val='+encodeURIComponent(v))"
    ".then(r=>{"
      "if(!r.ok) throw new Error('HTTP '+r.status);"
      "setCamResMsg('Resolución aplicada','green');"
    "})"
    ".catch(()=>{"
      "setCamResMsg('No se pudo contactar con la cámara','red');"
    "});"
"}"

      "</script>"
    "</div>"
  "</body>"
  "</html>";


#endif
